const copy={
en:{eyebrow:'A CLEAR START TO EVERY SHIFT',headline:'One place.\nOne informed team.',description:'Keep invoice requests, responsibilities and progress together. Pick up where the last shift left off.',sample:'Invoice request · September 12–14',prepared:'PDF prepared',lab:'Synthetic demo · No real guest records',language:'Language',welcome:'WELCOME BACK',signin:'Sign in',hint:'Use your reception account to open the workspace.',username:'Username',password:'Password',show:'Show',hide:'Hide',help:'Need access or a password reset? Contact the person managing this demo.',footer:'Your work stays connected to your signed-in account.',invalid:'Invalid username or password.',limited:'Too many attempts. Try again in 10 minutes.',network:'Connection unavailable. Please try again.',busy:'Signing in…'},
de:{eyebrow:'KLARHEIT FÜR JEDE SCHICHT',headline:'Ein Ort.\nEin informiertes Team.',description:'Rechnungswünsche, Zuständigkeiten und Fortschritt an einem Ort. Dort weitermachen, wo die letzte Schicht aufgehört hat.',sample:'Rechnungswunsch · 12.–14. September',prepared:'PDF vorbereitet',lab:'Synthetische Demo · Keine echten Gästedaten',language:'Sprache',welcome:'WILLKOMMEN ZURÜCK',signin:'Anmelden',hint:'Melde dich mit deinem Rezeptionskonto an.',username:'Benutzername',password:'Passwort',show:'Anzeigen',hide:'Verbergen',help:'Zugang oder neues Passwort benötigt? Wende dich an die Person, die diese Demo verwaltet.',footer:'Deine Arbeit wird deinem angemeldeten Konto zugeordnet.',invalid:'Benutzername oder Passwort ungültig.',limited:'Zu viele Versuche. Bitte in 10 Minuten erneut versuchen.',network:'Keine Verbindung. Bitte erneut versuchen.',busy:'Anmeldung…'},
it:{eyebrow:'OGNI TURNO PARTE CON CHIAREZZA',headline:'Un solo spazio.\nUn team informato.',description:'Richieste di fattura, responsabilità e avanzamento nello stesso posto. Riprendi da dove si è fermato il turno precedente.',sample:'Richiesta fattura · 12–14 settembre',prepared:'PDF preparato',lab:'Demo sintetica · Nessun dato reale degli ospiti',language:'Lingua',welcome:'BENTORNATA, BENTORNATO',signin:'Accedi',hint:'Usa il tuo account reception per aprire lo spazio di lavoro.',username:'Nome utente',password:'Password',show:'Mostra',hide:'Nascondi',help:'Ti serve un accesso o una nuova password? Contatta chi gestisce questa demo.',footer:'Le operazioni vengono associate al tuo account autenticato.',invalid:'Nome utente o password non validi.',limited:'Troppi tentativi. Riprova tra 10 minuti.',network:'Connessione non disponibile. Riprova.',busy:'Accesso in corso…'}};
let language='en';try{language=localStorage.getItem('invoice-language')||'en';}catch{}if(!copy[language])language='en';let errorKey='';
const $=s=>document.querySelector(s);
function localize(){document.documentElement.lang=language;document.querySelectorAll('[data-text]').forEach(e=>{e.textContent=copy[language][e.dataset.text];});$('h1').style.whiteSpace='pre-line';$('#language').value=language;$('#show-password').textContent=copy[language][$('#password').type==='password'?'show':'hide'];$('#login-error').textContent=errorKey?copy[language][errorKey]:'';}
$('#language').onchange=e=>{language=e.target.value;try{localStorage.setItem('invoice-language',language);}catch{}localize();};
$('#show-password').onclick=()=>{const show=$('#password').type==='password';$('#password').type=show?'text':'password';$('#show-password').setAttribute('aria-pressed',String(show));localize();};
$('#login-form').onsubmit=async e=>{e.preventDefault();errorKey='';$('#login-error').textContent='';$('#submit').disabled=true;$('#submit').textContent=copy[language].busy;try{const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('#username').value,password:$('#password').value})});if(r.ok){location.replace('/');return;}errorKey=r.status===429?'limited':r.status===401?'invalid':'network';}catch{errorKey='network';}$('#submit').disabled=false;localize();};localize();
